### ISSUE TITLE
Game opens offscreen

### ISSUE THREAD

**Issue by MichaelHinrichs** [Taifuun1/Amulet-Of-Iovar#1]
**Describe the bug**
The game window is opening partly off screen. the top edge of the window that i would be able to click and drag onscreen goes off the edge of my monitor.

**To Reproduce**
Open the game in Windows 7, on a HP S2031 monitor, at a resolution of 1600 x 900.

**Expected behavior**
The game opens with the window fully on screen.

**Screenshots**
![Amulet-Of-Iovar](https://github.com/Taifuun1/Amulet-Of-Iovar/assets/37460517/51ba71b3-2c7f-46ad-87b0-4b199ae3c95a)

**Comment by Taifuun1** [comment]
Fixed this in [3a596d2752429a012f1066393ee1e6ee1ac9287f](https://github.com/Taifuun1/Amulet-Of-Iovar/commit/3a596d2752429a012f1066393ee1e6ee1ac9287f)
